### ISSUE TITLE
Class 'App\Http\Controllers\System\TimeReq' not found

### ISSUE THREAD

**Issue by abdulmoiz29** [filippotoso/travelport#2]
Hi ,

I have downloaded your library and having issues while using it. Its been a week i have tried many things but nothings seems to work keep getting error "Class 'App\Http\Controllers\System\TimeReq' not found" with this example. I have copied the same code you have shown on the github after installing. If possible i would like you to help me fix it or give me a working laravel copy of the code. Thank you in advance.

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Travelport;

class HomeController extends Controller {

    public function test() {

// Create a Time request on the System service
        $request = (new System\TimeReq())
                ->setBillingPointOfSaleInfo(new System\BillingPointOfSaleInfo('UAPI')); // Don't know what this is, but it's required to complete a call :(
// Execute the request
        $response = Travelport::execute($request);
        printf('The current system time is %s', $response->getSystemTime());

// Create a Ping request on the System service
        $request = (new System\PingReq())
                ->setPayload('Hello World!')
                ->setBillingPointOfSaleInfo(new System\BillingPointOfSaleInfo('UAPI')); // Don't know what this is, but it's required to complete a call :(
// Execute the request
        $response = Travelport::execute($request);
        printf('Travelport pinged back: %s', $response->getPayload());
    }

}

**Comment by filippotoso** [comment]
You have to import the right namespaces.
