### ISSUE TITLE
Exception Classes Not Defined

### ISSUE THREAD

**Issue by Hayat-Umar** [filippotoso/travelport#4]
Hi,
First of all i must say that you did an awesome job by developing this library. I just start using this and got to know that Exception classes which you're calling in your code actually does not exists in library. Like 

```
FilippoToso\Travelport\Exceptions\MissingBindingsException
FilippoToso\Travelport\Exceptions\InvalidRegionException
```

**Comment by filippotoso** [comment]
Fixed in 2.1.2
