### ISSUE TITLE
Use Previous Response Data into Next Request

### ISSUE THREAD

**Issue by Hayat-Umar** [filippotoso/travelport#5]
Hi,
Typical flow for Air Booking is normally as following:

` LowFareSearchReq > AirPriceReq > SeatMapReq > AirCreateReservationReq > AirTicketing`

My question is that how can we use previous response data in next request like we always need airsegments/connections/passengers and all these.

**Comment by filippotoso** [comment]
Don't know for sure, never developed an air booking flow with this library.
As every request and response is represented as an object, I suspect it can be done setting the request parameter of subsequent request using the object in the previous responses.
