### ISSUE TITLE
How can I get the detail of segmentRef? 

### ISSUE THREAD

**Issue by rizwansaleem70** [filippotoso/travelport#7]
Hello ,

I'm getting the list of all flights, with the reference of Segment (SegmentRef) in AirPricePointList and also getting the AirSegmentList, FareInfoList etc. How can I get the AirSegmentList reference detail ?

AirPricePointList
![Screenshot_3](https://user-images.githubusercontent.com/10451770/67166610-6e2ddc80-f3aa-11e9-8361-d1e52acb29bd.png)

FareInfo Detail:
![Screenshot_5](https://user-images.githubusercontent.com/10451770/67166608-6e2ddc80-f3aa-11e9-9355-9c79a6a93a8f.png)

AirSegmentList:
![Screenshot_4](https://user-images.githubusercontent.com/10451770/67166611-6e2ddc80-f3aa-11e9-8d03-72fb0a0632bd.png)

**Comment by filippotoso** [comment]
Loop through the list of elements and extract the item with the same Key.
