### ISSUE TITLE
LowFareSearchReq Examples

### ISSUE THREAD

**Issue by DoDSoftware** [filippotoso/travelport#8]
Are there any examples available showing the use of LowFareSearchReq? Specifically for a roundtrip flight

**Comment by filippotoso** [comment]
The Travelport API is very complex. You have to read the documentation in order to understand which properties must be filled and with what.

Here is just a mockup:
  
```php
$traceId = sha1('my-unique-token');
$providerCode = '1G'; // Galileo

$travelport = new Travelport\Travelport(
    'Universal API/uAPI987654321', // Travelport User ID 
    'password', // Travelport Password     
    'P12345678', // Travelport Target Branch
    Travelport\Endpoints::REGION_EMEA, // Region
    false, // Set to false to use pre-production endpoints
    null
);

function searchPassenger()
{
    return (new Air\SearchPassenger)
        ->setCode('ADT');
}

function lowFareSearch($travelport, $traceId, $fromAirport, $toAirport, $date)
{

    $searchAirLeg = (new Air\SearchAirLeg)
        ->setSearchOrigin([
            (new Air\typeSearchLocation)->setAirport((new Air\Airport)->setCode($fromAirport)),
        ])
        ->setSearchDestination([
            (new Air\typeSearchLocation)->setAirport((new Air\Airport)->setCode($toAirport)),
        ])
        ->setSearchDepTime([
            (new Air\typeFlexibleTimeSpec)->setPreferredTime($date)
        ]);

    $searchPassenger = searchPassenger();

    $provider = (new Air\Provider())->setCode('1G');

    $preferredProviders = (new Air\PreferredProviders())
        ->setProvider($provider);

    $airSearchModifiers = (new Air\AirSearchModifiers())
        ->setPreferredProviders($preferredProviders);

    $request = (new Air\LowFareSearchReq())
        ->setBillingPointOfSaleInfo(new System\BillingPointOfSaleInfo('UAPI'))
        ->setAirSearchModifiers($airSearchModifiers)
        ->setSearchAirLeg($searchAirLeg)
        ->setSearchPassenger($searchPassenger)
        ->setTraceId($traceId);

    $response = $travelport->execute($request);

    return $response;
}

$date = date('Y-m-d', time() + 60 * 60 * 24 * 55); // 60 days in the future
$lowFareSearch = lowFareSearch($travelport, $traceId, 'LAX', 'SEA', $date);
```

**Comment by DoDSoftware** [comment]
@filippotoso Thank you, that all makes sense and was clear from the code. However, what we're wondering is how one would go about setting the return date for a round trip flight search.

Forgive me if I've missed something but this example only specifies the departure date, correct? How do we set the return date with this package?

**Comment by filippotoso** [comment]
As I said, you should read the Travelport documentation:

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_(Synchronous).htm

> Many Low Cost Carriers in ACH return only single, one-way fares, which requires the user to select two Air Pricing Solutions from a list of multiple fare options to complete a round-trip itinerary. Each instance of AirItinerarySolutionRef references a single one-way trip. References from both the first group (inbound) and the second group (outbound) in AirItinerarySolution are required for a round-trip itinerary.

**Comment by DoDSoftware** [comment]
Ah, apologies. Thanks for the answer. Is it accurate to say that this package supports setting just a single SearchAirLeg per LowFareSearchReq?


The schema supports setting up to 9 SearchAirLeg elements 
```
                    <xs:choice>
                        <xs:element ref="SearchAirLeg" maxOccurs="9"/>
                        <xs:element ref="SearchSpecificAirSegment" maxOccurs="999"/>
                    </xs:choice>
```

The documentation also specifies the below indicating that multiple legs are allowed:

> For ACH: AirPricingSolution returns a list of flights and prices for each leg of the itinerary, or pricing for complete itineraries when PreferCompleteItinerary=”true” and SolutionResult=”true”. Because Universal API combines ACH flights, some combinations are returned that may not be bookable, due to supplier restrictions.

**Comment by filippotoso** [comment]
The library code is autogenerated from the WSDLs. I don't know if the generator supports 100% of the Travelport WSDLs. As soon as I start working on a project with them I'll check.
